name: KingdomKits
version: ${project.version}
author: Ninjoh
main: tk.martijn_heil.kingdomkits.KingdomKits
depend: [Essentials]
softdepend: [Factions,MassiveCore]
commands:
   kingdomkits:
      aliases: [kk]
      description: The main command for this plugin.
      usage: /<command>
permissions:
    kingdomkits.*:
        description: Gives access to all kingdomkits permissions & commands.
        children:
#            kingdomkits.bind: true
            kingdomkits.setclass: true
            kingdomkits.setclass.class.*: true
            kingdomkits.setclass.others: true
            kingdomkits.getclass: true
            kingdomkits.getclass.others: true
            kingdomkits.list: true
            kingdomkits.bypass.*: true

    kingdomkits.bypass.*:
        description: Gives access to all kingdomkits bypass permissions.
        children:
            kingdomkits.bypass.factions.factionmembershipchangeevent: true
            kingdomkits.bypass.generic.changeclasscooldown: true
            kingdomkits.bypass.event.disableElytra: true
#    kingdomkits.bind:
#        default: op
    kingdomkits.list:
        default: true
    kingdomkits.setclass:
        default: op
    kingdomkits.setclass.class.*:
        default: op
    kingdomkits.setclass.others:
        default: op
    kingdomkits.getclass:
        default: true
    kingdomkits.getclass.others:
        default: true


    kingdomkits.bypass.factions.factionmembershipchangeevent:
        default: op
    kingdomkits.bypass.generic.changeclasscooldown:
        default: op
    kingdomkits.bypass.event.disableElytra:
        default: op


    kingdomkits.signs.create.switchclass:
        default: op